name: Build Test Publish
on: push

jobs:
  build-and-publish:
    name: Build, test, build docs, publish docs and publish to PyPI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install and upgrade pip, setuptools and wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install packages needed for testing and building
        run: python -m pip install jax[cpu] pytest build .

      - name: Run tests
        run: python -m pytest tests

      - name: Install jaxga and sphinx
        if: contains(github.ref, 'master')
        run: python -m pip install sphinx

      - name: Run sphinx
        if: contains(github.ref, 'master')
        run: sphinx-apidoc -o docs src/jaxga sphinx-apidoc --full -A "Robin 'Tora' Kahlow" && cd docs && make html

      - name: Push documentation to pages
        if: contains(github.ref, 'master')
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: 'docs/_build/html'

      - name: Build dist
        run: python -m build

      - name: Publish to test PyPI
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
